# Concert Halls
Esplanade Theatre:
    keywords:
        - Esplanade Theatre
        - Theatres on the Bay
        - Esplanade Concert

SOTA Concert Hall:
    keywords:
        - Sota Concert Hall

Star Performing Arts Centre:
    keywords:
        - Star Performing Arts Centre
        - Star Theatre Singapore

Zepp@BIGBOX:
    keywords:
        - Zepp@BigBOX

University Cultural Centre:
    keywords:
        - UCC Hall Singapore
        - University Cultural Centre NUS

Lee Foundation Theatre:
    keywords:
        - Lee Foundation Theatre

Capitol Theatre Singapore:
    keywords:
        - Capitol Theatre Singapore

Victoria Theatre and Concert Hall:
    keywords:
        - Victoria Theatre and Concert Hall
        - Victoria Theatre Singapore
        - Victoria Concert Singapore

Festive Grand Theatre:
    keywords:
        - Festive Grand Theatre Singapore

# Stadiums
Bukit Gombak Stadium:
    keywords:
        - Bukit Gombak Stadium

Jurong Stadium:
    keywords:
        - Jurong Stadium

Woodlands Stadium:
    keywords:
        - Woodlands Stadium

Bishan Stadium:
    keywords:
        - Bishan Stadium

Jurong East Stadium:
    keywords:
        - Jurong East Stadium

Jurong West Stadium:
    keywords:
        - Jurong West Stadium

Yio Chu Kang Stadium:
    keywords:
        - Yio Chu Kang Stadium
        - YCK Stadium

Clementi Stadium:
    keywords:
        - Clementi Stadium

Jalan Besar Stadium:
    keywords:
        - Jalan Besar Stadium

Toa Payoh Stadium:
    keywords:
        - Toa Payoh Stadium

Bedok Stadium:
    keywords:
        - Bedok Stadium

Yishun Stadium:
    keywords:
        - Yishun Stadium

Tampines Stadium:
    keywords:
        - Tampines Stadium

Singapore National Stadium:
    keywords:
        - Singapore National Stadium
        - Singapore Sports Hub

Choa Chu Kang Stadium:
    keywords:
        - Choa Chu Kang Stadium
        - Chua Chu Kang Stadium
        - CCK Stadium

Singapore Indoor Stadium:
    keywords:
        - Singapore Indoor Stadium

Marina Bay Floating Platform:
    keywords:
        - Marina Bay Floating Platform
        - Float@Marina Bay

# Museums
Singapore Art Museum:
    keywords:
        - Singapore Art Museum

Asian Civilisations Museum:
    keywords:
        - Asian Civilisations Museum

National Gallery Singapore:
    keywords:
        - National Gallery Singapore

National Museum of Singapore:
    keywords:
        - National Museum of Singapore

Peranakan Museum:
    keywords:
        - Peranakan Museum

Singapore Art Museum:
    keywords:
        - Singapore Art Museum

Artscience Museum:
    keywords:
        - Artscience Museum
        - Artscimuseum

Madame Tussauds Singapore:
    keywords:
        - Madame Tussauds Singapore

Maritime Experiential Museum & Aquarium:
    keywords:
        - Maritime Experiential Museum & Aquarium

S.E.A Aquarium:
    keywords:
        - S.E.A Aquarium


# Parks
Hong Lim Park:
    keywords:
        - Hong Lim Park

Changi Beach Park:
    keywords:
        - Changi Beach Park

East Coast Park:
    keywords:
        - East Coast Park

West Coast Park:
    keywords:
        - West Coast Park

Labrador Park:
    keywords:
        - Labrador Park Singapore

Bishan-Ang Mo Kio Park:
    keywords:
        - Bishan-Ang Mo Kio Park
        - Bishan-AMK Park

Ang Mo Kio Town Garden East:
    keywords:
        - Ang Mo Kio Town Garden East
        - AMK Garden East

Ang Mo Kio Town Garden West:
    keywords:
        - Ang Mo Kio Town Garden West
        - AMK Garden West

Bedok Town Park:
    keywords:
        - Bedok Town Park

Clementi Woods Park:
    keywords:
        - Clementi Woods Park

Pasir Ris Town Park:
    keywords:
        - Pasir Ris Town Park

Punggol Park:
    keywords:
        - Punggol Park

Woodlands Town Garden:
    keywords:
        - Woodlands Town Garden

Kent Ridge Park:
    keywords:
        - Kent Ridge Park

Mount Faber Park:
    keywords:
        - Mount Faber Park

The Southern Ridges:
    keywords:
        - Southern Ridges

Henderson Waves:
    keywords:
        - Henderson Wave

Telok Blangah Hill Park:
    keywords:
        - Telok Blangah Hill Park

Dairy Farm Nature Park:
    keywords:
        - Dairy Farm Nature Park

Bukit Batok Nature Park:
    keywords:
        - Bukit Batok Nature Park

HortPark:
    keywords:
        - HortPark
        - Hort Park

Merlion Park:
    keywords:
        - Merlion Park

Bukit Batok Town Park:
    keywords:
        - Bukit Batok Town Park
        - Xiao Guilin

Bukit Timah Hill:
    keywords:
        - Bukit Timah Hill

Sungei Buloh Wetland Reserve:
    keywords:
        - Sungei Buloh Wetland

Padang:
    keywords:
        - Padang Singapore

# Reservoirs
Bedok Reservoir:
    keywords:
        - Bedok Reservoir

Jurong Lake:
    keywords:
        - Jurong Lake

Lower Peirce Reservoir:
    keywords:
        - Lower Peirce Reservoir

Lower Seletar Reservoir:
    keywords:
        - Lower Seletar Reservoir

MacRitchie Reservoir:
    keywords:
        - MacRitchie Reservoir

Upper Peirce Reservoir:
    keywords:
        - Upper Peirce Reservoir

Upper Seletar Reservoir:
    keywords:
        - Upper Seletar Reservoir

# Beaches
Palawan Beach:
    keywords:
        - Palawan Beach Sentosa
        - Palawan Beach Singapore

Tanjong Beach:
    keywords:
        - Tanjong Beach Sentosa
        - Tanjong Beach Singapore

Siloso Beach:
    keywords:
        - Siloso Beach


# Tourist sites
Science Centre Singapore:
    keywords:
        - Science Centre Singapore

Singapore Discovery Centre:
    keywords:
        - Singapore Discovery Centre

Wild Wild Wet:
    keywords:
        - Wild Wild Wet

Helix Bridge:
    keywords:
        - Helix Bridge

Jurong Bird Park:
    keywords:
        - Jurong Bird Park

Night Safari:
    keywords:
        - Night Safari Singapore

River Safari:
    keywords:
        - River Safari Singapore

Singapore Zoo:
    keywords:
        - Singapore Zoo

Marina Barrage:
    keywords:
        - Marina Barrage

Malay Heritage Centre:
    keywords:
        - Malay Heritage Centre

Istana:
    keywords:
        - Istana Singapore

Thian Hock Keng Temple:
    keywords:
        - Thian Hock Keng Temple


# Expo halls
Marina Bay Sands:
    keywords:
        - Marina Bay Sands

Changi Exhibition Centre:
    keywords:
        - Changi Exhibition Centre

MAX Atria:
    keywords:
        - MAX Atria

Raffles City Convention Centre:
    keywords:
        - Raffles City Convention Centre

Singapore Conference Hall:
    keywords:
        - Singapore Conference Hall

Suntec Convention Centre:
    keywords:
        - Suntec Convention Centre

Resorts World Sentosa:
    keywords:
        - Resorts World Sentosa

# Districts
Boat Quay:
    keywords:
        - Boat Quay

# Shopping centre
Far East Plaza:
    keywords:
        - Far East Plaza

Liang Court:
    keywords:
        - Liang Court

Mustafa Centre:
    keywords:
        - Mustafa Centre

People's Park Complex:
    keywords:
        - People's Park Complex

Plaza Singapura:
    keywords:
        - Plaza Singapura

Sim Lim Square:
    keywords:
        - Sim Lim Square

Tekka Centre:
    keywords:
        - Tekka Centre

112 Katong:
    keywords:
        - 112 Katong

Bedok Mall:
    keywords:
        - Bedok Mall

Kallang Wave Mall:
    keywords:
        - Kallang Wave Mall

Leisure Park Kallang:
    keywords:
        - Leisure Park Kallang

Causeway Point:
    keywords:
        - Causeway Point

Tanjong Pagar Railway Station:
    keywords:
        - Tanjong Pagar Railway Station
